---
  - name: My first playbook
    hosts: webservers
    become: true
    tasks:
    
    - name: Install docker.io  with ansible apt
      apt:
        name: docker
        state: present
    - name: Install python3-pip
	apt:
	 name: python3-pip
    - name: Install docker with pip module
      pip:
	name: docker
    - name: docker-container
	cyberxsecurity/dvwa
	expose:
	 - 800
